# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vlwr500NSZ_8Gpyq7DReD6jrkJAEv2mL
"""

# app.py
import streamlit as st
import pandas as pd
from pricing_engine import run_pricing_engine
import matplotlib.pyplot as plt
import numpy as np

st.set_page_config(page_title="SmartPrice AI", layout="wide")
st.title("SmartPrice AI – Dynamic Pricing Engine")
st.markdown("### Upload your sales data → Get AI-powered optimal prices in 60 seconds")

col1, col2 = st.columns(2)
with col1:
    retail_file = st.file_uploader("Upload Transactions (online_retail_II.csv)", type=["csv"])
with col2:
    demand_file = st.file_uploader("Upload Daily Sales (retail_store_inventory.csv)", type=["csv"])

if retail_file and demand_file:
    retail_df = pd.read_csv(retail_file)
    demand_df = pd.read_csv(demand_file)

    if st.button("Run AI Pricing Engine", type="primary", use_container_width=True):
        with st.spinner("Training model & calculating optimal prices..."):
            results_df, avg_uplift, r2 = run_pricing_engine(retail_df, demand_df)

        st.success(f"Done! Model Accuracy (R²): {r2:.3f} | Average Revenue Uplift: +{avg_uplift:.1f}%")

        # Metrics
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Products Analyzed", len(results_df))
        c2.metric("Price Increases Recommended", len(results_df[results_df['price_change_%'] > 0]))
        c3.metric("Price Decreases Recommended", len(results_df[results_df['price_change_%'] < 0]))
        c4.metric("Expected Revenue Gain", f"+{avg_uplift:.1f}%", delta=f"+{avg_uplift:.1f}%")

        st.subheader("Optimal Pricing Recommendations")
        st.dataframe(results_df.sort_values('revenue_uplift_%', ascending=False), use_container_width=True)

        st.download_button(
            label="Download Full Report (CSV)",
            data=results_df.to_csv(index=False).encode(),
            file_name="smartprice_recommendations.csv",
            mime="text/csv"
        )

        # Interactive Demand Curve
        st.subheader("Explore Demand Curve")
        pid = st.selectbox("Select Product ID", results_df['product_id'].unique())
        row = results_df[results_df['product_id'] == pid].iloc[0]
        base = row['current_price']
        prices = np.round(base * np.array([0.8, 0.9, 1.0, 1.1, 1.2]), 2)

        # Simulate curve
        sales = []
        revenues = []
        for p in prices:
            # Simplified prediction (you can reuse model + encoder if you pass them)
            pred_sales = 100 * (base / p) ** 0.8  # mock elasticity
            sales.append(pred_sales)
            revenues.append(pred_sales * p)

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
        ax1.plot(prices, sales, 'o-', color='steelblue')
        ax1.set_title("Demand Curve"); ax1.set_xlabel("Price"); ax1.set_ylabel("Units Sold")
        ax2.plot(prices, revenues, 'o-', color='green')
        ax2.axvline(row['optimal_price'], color='red', linestyle='--', label=f"Optimal = {row['optimal_price']}")
        ax2.legend(); ax2.set_title("Revenue Curve"); ax2.set_xlabel("Price")
        st.pyplot(fig)

else:
    st.info("Please upload both CSV files to begin.")
    st.markdown("""
    **Sample files available here:**
    → [online_retail_II.csv](https://raw.githubusercontent.com/sivabalan01/smartprice-ai/main/sample_data/online_retail_II.csv)
    → [retail_store_inventory.csv](https://raw.githubusercontent.com/sivabalan01/smartprice-ai/main/sample_data/retail_store_inventory.csv)
    """)
